### ISSUE TITLE
Discordant no longer has a function makeTable()

### ISSUE THREAD

**Issue by ryananeff** [andymckenzie/dgca_manuscript#1]
https://github.com/andymckenzie/dgca_manuscript/blob/79d3fb6c4ffcba19aefefba2ba9b76565e3f1f2c/sim_roc_classes.R#L522

**Comment by andymckenzie** [comment]
As you note it's present in an older version: makeTable is present in Discordant version 0.99.0, which was the version used in the manuscript. Unfortunately, this script only works with Discordant version 0.99.0, not the current version.
